### ISSUE TITLE
Feedback about "trusted" feature

### ISSUE THREAD

**Issue by nscozzaro** [mflevine/jupyterlab_html#12]
Hi, I just wanted to give some quick feedback about the "trust" feature. I initially didn't see that button, so my suggestion is to add some sort of alert message if scripts are being blocked to draw the user's attention to that button. Or maybe a different styling for the button to indicate that the file contains javascript that is being blocked. 

To be clear, this is the button I'm referring to:
![image](https://user-images.githubusercontent.com/15185105/65919722-2fa89180-e3ab-11e9-8c5c-f5387c17bf55.png)

I wanted to alert you to this because I spent time trying to debug the error I was seeing in my console when my file wouldn't load, and it would be nice to improve the UI of this feature so that others don't miss it too!
```
Blocked script execution in 'blob:<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```
![image](https://user-images.githubusercontent.com/15185105/65919779-55359b00-e3ab-11e9-8383-645993d691ca.png)

**Comment by mflevine** [comment]
Hi, the viewer has been merged into core and is no longer developed here. The "trust" feature is only there. Maybe post this there.
