### ISSUE TITLE
A README.md revamp

### ISSUE THREAD

**Issue by consideRatio** [mflevine/jupyterlab_html#2]
I'm arriving to this repo from [this page which lists jupyterlab extensions](https://github.com/topics/jupyterlab-extension). In it I also saw the [jupyterlab_iframe extension](https://github.com/timkpaine/jupyterlab_iframe) listed. I ended up confused about the difference between these extensions and uncertain about what this extension do.

Perhaps the README.md could elaborate?

**Comment by mflevine** [comment]
@consideRatio The two extensions are similar. This one currently is only a mimerenderer for .html files which means that it will let you open .html files from the files tab by double clicking on them or using the open with. The iframe extension I dont think currently does this but allows you to open a url from commands tab. Hope this helps. I might make this more explicit in the README

**Comment by consideRatio** [comment]
Ah! That was a very meaningful explanation to me! Now I know that this is a plugin I want to install :)

Thank you!

**Comment by cooknl** [comment]
Yes, a statement to the effect of "Motivation: Before installing, there is no way for Y to happen. Instructions: After installing, do X and Y will happen."

**Comment by mflevine** [comment]
I have added a little more text and an example gif!
