### ISSUE TITLE
Using CSS files

### ISSUE THREAD

**Issue by manuelknott** [mflevine/jupyterlab_html#4]
Is it possible to use HTML Files together with CSS files?

I am trying to include a sphinx-built documentation file to my Jupyter Lab Project.

**Comment by mflevine** [comment]
The current issue is relative links, in general, are not being handled. There some code in the core for handling relative links in HTML rendering but it also strips out the javascript.

**Comment by manuelknott** [comment]
So if I understand you right, I can use external CSS if I do not need Javascript? If yes, can you give me a hint how to do so / where to find the said code?

**Comment by mflevine** [comment]
Sorry I think I misunderstood your question. You can use external CSS as long as you give the full path to the CSS file. Relative URLs are not currently supported. 
You can do this:
`<link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Open+Sans'>`

**Comment by manuelknott** [comment]
Ok now I got it. Thanks for the explanation.

So refering to a css style which lies within my Jupyter Lab tree should look like this?

`<link rel="stylesheet" type="text/css" href='http://localhost:8888/lab/tree/styles.css'>`

**Comment by mflevine** [comment]
Jupyter hosts the file server under localhost:port/files so I think it would be:
`<link rel="stylesheet" type="text/css" href='http://localhost:8888/files/styles.css'>`
Although it might autoredirect.

**Comment by manuelknott** [comment]
It works with the solution in your last comment. Thank you very very much 👍 ,
