### ISSUE TITLE
Migrate to core JupyterLab?

### ISSUE THREAD

**Issue by ian-r-rose** [mflevine/jupyterlab_html#7]
Hi @mflevine, thanks for putting this together!

At the JupyterLab developers meeting this week we were discussing the usefulness of this functionality. Do you have any interest in graduating this extension to the core of JupyterLab? We could rebase it so that we preserve your commits for credit purposes.

Are you aware of any missing/broken functionality here that should be addressed in the near-term? We would certainly be willing to help on that front. It looks to me like relative links to resources don't work at the moment. I have some ideas about how we might fix that, which would require some changes to the rendermime extension API.

**Comment by mflevine** [comment]
Hi @ian-r-rose,
I would love for this extension to be integrated into core JupyterLab.
As for missing/broken functionality, you are absolutely correct about relative links. When I was developing the extension I had looked into this, and I remember seeing this solved in other parts of JupyterLab. Please let me know how we can move forward with this.

**Comment by ian-r-rose** [comment]
I have two PRs in mind which I'd like to make to this repo, and then we can transfer it to core.

1. I think we can reuse the [`IFrame`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/iframe.ts) widget in apputils to avoid duplicating some code that is in the core.
2. I did some experimentation yesterday: I think we can set the [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element in the renderer to get relative links working (for the purposes of style sheets and scripts).

We may be able to do some fancier stuff to get linked documents to open in new JupyterLab tabs, but I think that can wait for later.

EDIT: sorry, misclick.

**Comment by mflevine** [comment]
Sounds great!

**Comment by ian-r-rose** [comment]
Great! PRs incoming soon.

Thanks again @mflevine!

**Comment by davidrpugh** [comment]
Has then been merged into Jupyterlab Core? Can't find any documentation on this...

**Comment by mflevine** [comment]
It was merged in this pull request https://github.com/jupyterlab/jupyterlab/pull/5855. I have not used it from the core yet but it appears here: https://github.com/jupyterlab/jupyterlab/tree/master/packages/htmlviewer. As far as I know they have added some changes for security.

**Comment by aarondewindt** [comment]
Core version seems to be working and installing this extension on the latest JupyterLab is failing. Maybe we should add a notice about this in the project's readme? Something in the line of, "no need to install if using Jupyter>=##.##".

**Comment by mflevine** [comment]
Done.
